# Módelos Machine Learning

In [3]:
# seleccionar la fecha del csv
import os
import pandas as pd
# Definir ruta del archivo
directorio = '../data/processed/'
nombre_archivo_trabajo = 'actividades(261)_detalles_depuradoML_02mayo2025.csv'
ruta_archivo_trabajo = os.path.join(directorio, nombre_archivo_trabajo)

df = pd.read_csv(ruta_archivo_trabajo)

In [4]:
df.head()

,edad_min,edad_max,requiere_inscripcion,hora_inicio,hora_fin,precio_valor,recomendado,tiene_url_info,tiene_url_imagen,titulo_longitud,...,distrito_Carabanchel,distrito_Barajas,distrito_Moncloa-Aravaca,distrito_Fuencarral-El Pardo,distrito_Villaverde,precio_gratuito,precio_bajo,precio_medio,precio_alto,ciudad_Madrid
0,0.034213,0.061509,0,-1.291316,-1.271095,-0.063246,1,0,1,0.127032,...,0,0,0,0,0,1,0,0,0,1
1,1.687835,-0.911454,1,0.875340,0.654059,-0.063246,1,1,0,0.905329,...,0,0,0,0,0,1,0,0,0,1
2,2.018559,-0.911454,1,0.875340,0.654059,-0.063246,1,1,1,0.905329,...,0,0,0,0,0,1,0,0,0,1
3,1.687835,-1.154695,1,0.720579,0.505970,-0.063246,1,1,1,1.372307,...,0,0,0,0,0,1,0,0,0,1
4,2.018559,-0.911454,1,0.875340,0.654059,-0.063246,1,1,1,0.801556,...,0,0,0,0,0,1,0,0,0,1

In [11]:
df.describe()

,edad_min,edad_max,requiere_inscripcion,hora_inicio,hora_fin,precio_valor,recomendado,tiene_url_info,tiene_url_imagen,titulo_longitud,...,distrito_Carabanchel,distrito_Barajas,distrito_Moncloa-Aravaca,distrito_Fuencarral-El Pardo,distrito_Villaverde,precio_gratuito,precio_bajo,precio_medio,precio_alto,ciudad_Madrid
count,261.000000,2.610000e+02,261.000000,2.610000e+02,2.610000e+02,2.610000e+02,261.0,261.000000,261.000000,2.610000e+02,...,261.000000,261.000000,261.000000,261.000000,261.000000,261.000000,261.000000,261.0,261.0,261.0
mean,0.000000,-5.444772e-17,0.241379,2.314028e-16,-5.444772e-17,3.402982e-17,1.0,0.777778,0.773946,1.327163e-16,...,0.034483,0.011494,0.003831,0.003831,0.011494,0.957854,0.003831,0.0,0.0,1.0
std,1.001921,1.001921e+00,0.428742,9.527289e-01,3.823007e-01,9.825399e-01,0.0,0.416538,0.419078,1.001921e+00,...,0.182816,0.106798,0.061898,0.061898,0.106798,0.201307,0.061898,0.0,0.0,0.0
min,-0.957960,-3.343862e+00,0.000000,-2.374644e+00,-2.455805e+00,-6.324555e-02,1.0,0.000000,0.000000,-1.481448e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,1.0
25%,-0.957960,-4.249725e-01,0.000000,-9.817933e-01,0.000000e+00,-6.324555e-02,1.0,1.000000,1.000000,-7.550375e-01,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.0,1.0
50%,0.034213,5.479908e-01,0.000000,2.562958e-01,0.000000e+00,-6.324555e-02,1.0,1.000000,1.000000,-2.361729e-01,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.0,1.0
75%,0.695662,5.479908e-01,0.000000,8.753404e-01,0.000000e+00,-6.324555e-02,1.0,1.000000,1.000000,6.458970e-01,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.0,1.0
max,3.672181,5.479908e-01,1.000000,1.494385e+00,1.246414e+00,1.581139e+01,1.0,1.000000,1.000000,4.693041e+00,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,1.0

## Modelo recomendación KNN

In [13]:
import pandas as pd
# from df_to_ml import df_to_ml
from sklearn.neighbors import NearestNeighbors

# Crear y entrenar el modelo KNN
model = NearestNeighbors(n_neighbors=5, algorithm='auto')
model.fit(df)

# Función para obtener recomendaciones dado un índice de actividad
def obtener_recomendaciones(indice_actividad, df_original, df_procesado, model, n_recommendations=5):
    """
    Obtiene recomendaciones de actividades similares a una actividad dada.
    
    Parámetros:
    -----------
    indice_actividad : int
        Índice de la actividad para la que se desean recomendaciones.
    df_original : DataFrame
        DataFrame original con toda la información.
    df_procesado : DataFrame
        DataFrame procesado usado para el modelo.
    model : NearestNeighbors
        Modelo KNN entrenado.
    n_recommendations : int, opcional (default=5)
        Número de recomendaciones a devolver.
        
    Retorna:
    --------
    DataFrame con las actividades recomendadas.
    """
    # Obtener las características de la actividad seleccionada
    actividad_seleccionada = df_procesado.iloc[indice_actividad].values.reshape(1, -1)
    
    # Encontrar los vecinos más cercanos
    distancias, indices = model.kneighbors(actividad_seleccionada, n_neighbors=n_recommendations+1)
    
    # Excluir la propia actividad (primera en la lista)
    indices = indices.flatten()[1:]
    distancias = distancias.flatten()[1:]
    
    # Crear DataFrame con las recomendaciones
    recomendaciones = df_original.iloc[indices].copy()
    recomendaciones['distancia'] = distancias
    
    # Ordenar por distancia (menor a mayor)
    recomendaciones = recomendaciones.sort_values('distancia')
    
    return recomendaciones

In [ ]:
# Ejemplo de uso
indice_ejemplo = 24  # Por ejemplo, la actividad "Chatines: club de lectura infantil"
recomendaciones = obtener_recomendaciones(indice_ejemplo, df_depurado2, df, model)
print(recomendaciones[['título', 'categoría', 'subcategoría', 'distancia']])

NameError: name 'df_depurado2' is not defined