# Módelos Machine Learning

## Carga de los datos guardados previamente

### 1. carga dataframe "original"

In [1]:
# seleccionar la fecha del csv en el caso de haber datos más recientes
import os
import pandas as pd
# Definir ruta del archivo
directorio = '../data/processed/'
nombre_archivo_trabajo = 'actividades(261)_detalles_depurado2_02mayo2025.csv'
ruta_archivo_trabajo = os.path.join(directorio, nombre_archivo_trabajo)

df_original = pd.read_csv(ruta_archivo_trabajo)

In [2]:
df_original = df_original.convert_dtypes()
df_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   título                261 non-null    string
 1   descripción           237 non-null    string
 2   categoría             261 non-null    string
 3   subcategoría          261 non-null    string
 4   edad_min              156 non-null    Int64
 5   edad_max              156 non-null    Int64
 6   requiere_inscripcion  63 non-null     boolean
 7   periodicidad          16 non-null     string
 8   día_días              259 non-null    string
 9   hora_inicio           236 non-null    string
 10  hora_fin              38 non-null     string
 11  fecha_inicio          256 non-null    string
 12  fecha_fin             256 non-null    string
 13  ciudad                261 non-null    string
 14  distrito              217 non-null    string
 15  precio_valor          251 non-null    Int64
 16  recomendado           261 non-null    boolean
 17  tiene_url_info        261 non-null    boolean
 18  tiene_url_imagen      261 non-null    boolean
dtypes: Int64(3), boolean(4), string(12)
memory usage: 33.5 KB

In [3]:
df_original.head(1)

,título,descripción,categoría,subcategoría,edad_min,edad_max,requiere_inscripcion,periodicidad,día_días,hora_inicio,hora_fin,fecha_inicio,fecha_fin,ciudad,distrito,precio_valor,recomendado,tiene_url_info,tiene_url_imagen
0,Talleres creativos en idioma serbio,Talleres creativos para niños y niñas de 3 a16...,Cultura y Espectáculos. Educación,Idiomas. Música. Talleres. Teatro Infantil,3,16,<NA>,<NA>,domingo,11:00,13:00,22/09/2024,22/06/2025,Madrid,Centro,0,True,False,True

### 2. carga dataframe listo ML

In [4]:
# seleccionar la fecha del csv
import os
import pandas as pd
# Definir ruta del archivo
directorio = '../data/processed/'
nombre_archivo_trabajo = 'actividades(261)_detalles_depuradoML_02mayo2025.csv'
ruta_archivo_trabajo = os.path.join(directorio, nombre_archivo_trabajo)

df_ml = pd.read_csv(ruta_archivo_trabajo)

In [5]:
df_ml.head()

,edad_min,edad_max,requiere_inscripcion,hora_inicio,hora_fin,precio_valor,recomendado,tiene_url_info,tiene_url_imagen,titulo_longitud,...,distrito_Carabanchel,distrito_Barajas,distrito_Moncloa-Aravaca,distrito_Fuencarral-El Pardo,distrito_Villaverde,precio_gratuito,precio_bajo,precio_medio,precio_alto,ciudad_Madrid
0,0.034213,0.061509,0,-1.291316,-1.271095,-0.063246,1,0,1,0.127032,...,0,0,0,0,0,1,0,0,0,1
1,1.687835,-0.911454,1,0.875340,0.654059,-0.063246,1,1,0,0.905329,...,0,0,0,0,0,1,0,0,0,1
2,2.018559,-0.911454,1,0.875340,0.654059,-0.063246,1,1,1,0.905329,...,0,0,0,0,0,1,0,0,0,1
3,1.687835,-1.154695,1,0.720579,0.505970,-0.063246,1,1,1,1.372307,...,0,0,0,0,0,1,0,0,0,1
4,2.018559,-0.911454,1,0.875340,0.654059,-0.063246,1,1,1,0.801556,...,0,0,0,0,0,1,0,0,0,1

In [6]:
df_ml.describe()

,edad_min,edad_max,requiere_inscripcion,hora_inicio,hora_fin,precio_valor,recomendado,tiene_url_info,tiene_url_imagen,titulo_longitud,...,distrito_Carabanchel,distrito_Barajas,distrito_Moncloa-Aravaca,distrito_Fuencarral-El Pardo,distrito_Villaverde,precio_gratuito,precio_bajo,precio_medio,precio_alto,ciudad_Madrid
count,261.000000,2.610000e+02,261.000000,2.610000e+02,2.610000e+02,2.610000e+02,261.0,261.000000,261.000000,2.610000e+02,...,261.000000,261.000000,261.000000,261.000000,261.000000,261.000000,261.000000,261.0,261.0,261.0
mean,0.000000,-5.444772e-17,0.241379,2.314028e-16,-5.444772e-17,3.402982e-17,1.0,0.777778,0.773946,1.327163e-16,...,0.034483,0.011494,0.003831,0.003831,0.011494,0.957854,0.003831,0.0,0.0,1.0
std,1.001921,1.001921e+00,0.428742,9.527289e-01,3.823007e-01,9.825399e-01,0.0,0.416538,0.419078,1.001921e+00,...,0.182816,0.106798,0.061898,0.061898,0.106798,0.201307,0.061898,0.0,0.0,0.0
min,-0.957960,-3.343862e+00,0.000000,-2.374644e+00,-2.455805e+00,-6.324555e-02,1.0,0.000000,0.000000,-1.481448e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,1.0
25%,-0.957960,-4.249725e-01,0.000000,-9.817933e-01,0.000000e+00,-6.324555e-02,1.0,1.000000,1.000000,-7.550375e-01,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.0,1.0
50%,0.034213,5.479908e-01,0.000000,2.562958e-01,0.000000e+00,-6.324555e-02,1.0,1.000000,1.000000,-2.361729e-01,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.0,1.0
75%,0.695662,5.479908e-01,0.000000,8.753404e-01,0.000000e+00,-6.324555e-02,1.0,1.000000,1.000000,6.458970e-01,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.0,1.0
max,3.672181,5.479908e-01,1.000000,1.494385e+00,1.246414e+00,1.581139e+01,1.0,1.000000,1.000000,4.693041e+00,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,1.0

## Modelo recomendación KNN
(primer ejemplo sin filtrado previo)

In [7]:
import pandas as pd
# from df_to_ml import df_to_ml
from sklearn.neighbors import NearestNeighbors

# Crear y entrenar el modelo KNN
model = NearestNeighbors(n_neighbors=5, algorithm='auto')
model.fit(df_ml)

# Función para obtener recomendaciones dado un índice de actividad
def obtener_recomendaciones(indice_actividad, df_original, df_procesado, model, n_recommendations=5):
    """
    Obtiene recomendaciones de actividades similares a una actividad dada.
    
    Parámetros:
    -----------
    indice_actividad : int
        Índice de la actividad para la que se desean recomendaciones.
    df_original : DataFrame
        DataFrame original con toda la información.
    df_procesado : DataFrame
        DataFrame procesado usado para el modelo.
    model : NearestNeighbors
        Modelo KNN entrenado.
    n_recommendations : int, opcional (default=5)
        Número de recomendaciones a devolver.
        
    Retorna:
    --------
    DataFrame con las actividades recomendadas.
    """
    # Obtener las características de la actividad seleccionada
    actividad_seleccionada = df_procesado.iloc[[indice_actividad]]
    
    # Encontrar los vecinos más cercanos
    distancias, indices = model.kneighbors(actividad_seleccionada, n_neighbors=n_recommendations+1)
    
    # Excluir la propia actividad (primera en la lista)
    indices = indices.flatten()[1:]
    distancias = distancias.flatten()[1:]
    
    # Crear DataFrame con las recomendaciones
    recomendaciones = df_original.iloc[indices].copy()
    recomendaciones['distancia'] = distancias
    
    # Ordenar por distancia (menor a mayor)
    recomendaciones = recomendaciones.sort_values('distancia')
    
    return recomendaciones

In [8]:
# Ejemplo de uso
indice_ejemplo = 24  # Por ejemplo, la actividad "Chatines: club de lectura infantil"
print(df_original.loc[indice_ejemplo,['título', 'categoría', 'día_días', 'distrito','subcategoría']])

recomendaciones = obtener_recomendaciones(indice_ejemplo, df_original, df_ml, model)
print(recomendaciones[['título', 'categoría', 'subcategoría', 'día_días', 'distrito', 'distancia']])

título          Chatines: club de lectura infantil
categoría                   Cultura y Espectáculos
día_días                                    jueves
distrito                                 Chamartín
subcategoría                       Club de lectura
Name: 24, dtype: object
                             título               categoría     subcategoría  \
171      'Había una vez una iguana'  Cultura y Espectáculos  Club de lectura
26                     Manualidades  Cultura y Espectáculos         Talleres
168               'Con mis manitas'  Cultura y Espectáculos  Club de lectura
227      'Había una vez una iguana'  Cultura y Espectáculos  Club de lectura
120  '1. 2, 3, dedos, manos y pies'  Cultura y Espectáculos  Club de lectura

      día_días       distrito  distancia
171     jueves         Tetuán   7.357439
26      martes          Usera   7.553315
168  miércoles        Barajas   7.587350
227    viernes  Ciudad Lineal   7.634443
120     martes      Chamartín   7.727684

In [9]:
df_original.iloc[[indice_ejemplo]]

,título,descripción,categoría,subcategoría,edad_min,edad_max,requiere_inscripcion,periodicidad,día_días,hora_inicio,hora_fin,fecha_inicio,fecha_fin,ciudad,distrito,precio_valor,recomendado,tiene_url_info,tiene_url_imagen
24,Chatines: club de lectura infantil,¿Qué es el Club de Lectura Chatines?,Cultura y Espectáculos,Club de lectura,9,12,True,<NA>,jueves,17:30,18:30,27/02/2025,19/06/2025,Madrid,Chamartín,0,True,False,True

In [10]:
recomendaciones

,título,descripción,categoría,subcategoría,edad_min,edad_max,requiere_inscripcion,periodicidad,día_días,hora_inicio,hora_fin,fecha_inicio,fecha_fin,ciudad,distrito,precio_valor,recomendado,tiene_url_info,tiene_url_imagen,distancia
171,'Había una vez una iguana',Nunca es demasiado pronto para iniciar a los b...,Cultura y Espectáculos,Club de lectura,<NA>,<NA>,True,<NA>,jueves,17:30,<NA>,22/05/2025,22/05/2025,Madrid,Tetuán,0,True,True,True,7.357439
26,Manualidades,"Taller de manualidades ideado, coordinado y ej...",Cultura y Espectáculos,Talleres,6,12,True,mensual,martes,18:00,19:30,25/03/2025,24/06/2025,Madrid,Usera,0,True,False,True,7.553315
168,'Con mis manitas',Nunca es demasiado pronto para iniciar a los b...,Cultura y Espectáculos,Club de lectura,<NA>,<NA>,True,<NA>,miércoles,17:30,<NA>,21/05/2025,21/05/2025,Madrid,Barajas,0,True,True,True,7.587350
227,'Había una vez una iguana',Nunca es demasiado pronto para iniciar a los b...,Cultura y Espectáculos,Club de lectura,<NA>,<NA>,True,<NA>,viernes,17:30,<NA>,30/05/2025,30/05/2025,Madrid,Ciudad Lineal,0,True,True,True,7.634443
120,"'1. 2, 3, dedos, manos y pies'",Nunca es demasiado pronto para iniciar a los b...,Cultura y Espectáculos,Club de lectura,<NA>,<NA>,True,<NA>,martes,17:30,<NA>,13/05/2025,13/05/2025,Madrid,Chamartín,0,True,True,True,7.727684

## Modelo recomendación KNN con filtrado previo

### Pasos previos de filtrado

In [11]:
# Valores permitidos de los filtros, condiciones o claves de busqueda:
categorias = [
    "La Ciudad", "Cultura y Espectáculos", "Educación", "Aire Libre", "Deporte"
]

subcategorias = {
    "La Ciudad": ["Actividades", "Carnaval", "Semana Santa", "Verano", "Centros de Atención a Las Familias", "Navidad"],
    "Cultura y Espectáculos": ["Cuentacuentos", "Títeres y marionetas", "Magia", "Club de lectura", "Cine Infantil", 
                               "Circo", "Conciertos", "Exposiciones", "Monumentos", "Museos", "Proyecciones", 
                               "Talleres", "Teatro Infantil", "Música", "Bailes"],
    "Educación": ["Ayudas y Becas", "Campamentos Urbanos", "Ludotecas", "Idiomas"],
    "Aire Libre": ["Actividades al Aire Libre", "Actividades con animales", "Parques y jardines"],
    "Deporte": ["Deportes de aventura", "Deportes de invierno", "Deportes acuáticos", "Deportes de cancha", 
                "Rocódromos", "Deporte en la calle", "Carreras y eventos"]
}

rango_edades_validos = [(0, 3), (4, 6), (7, 9), (10, 12), (13, 15), (16, 18)]
dias_validos = ["lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "día de semana", "fin de semana"]
periodicidad_valida = ["diaria", "semanal", "quincenal", "mensual"]
horarios_validos = ["mañana", "mediodía", "tarde", "noche"]
estaciones_validas = ["verano","invierno"]
duraciones_validas = ["corta", "media", "larga"]
distritos_madrid = ['Centro', 'Arganzuela', 'Retiro', 'Salamanca', 'Chamartín', 'Tetuán', 'Chamberí',
    'Fuencarral-El Pardo', 'Moncloa-Aravaca', 'Latina', 'Carabanchel', 'Usera',
    'Puente de Vallecas', 'Moratalaz', 'Ciudad Lineal', 'Hortaleza', 'Villaverde',
    'Villa de Vallecas', 'Vicálvaro', 'San Blas-Canillejas', 'Barajas']
precios_validos = ["gratuito", "bajo", "medio", "alto"]

# Mostrar posibles valores
print("🎯 Posibles valores para cada condición:")
print(f"- Rango de edad: {rango_edades_validos}")
print(f"- Fecha: formato 'dd/mm/aaaa'")
print(f"- Día: {dias_validos}")
print(f"- Periodicidad: {periodicidad_valida}")
print(f"- Horario: {horarios_validos}")
print("     Horarios; mañana (de 7 a 12h), mediodía (de 12 a 15h), tarde (de 15 a 19h) y noche (de 19 a 7h)")
print(f"- Estación: {estaciones_validas}")
print("     Unicamente se admite verano (de junio a septiembre) o invierno (de diciembre a febrero)")
print(f"- Duración: {duraciones_validas}")
print("     Intervalos: admite corta (1 día), media (entre 1 y 7 días) o larga (más de 7 días)")
print(f"- Distritos de Madrid: {distritos_madrid}")
print(f"- Ciudad: Madrid (obligatoria)")
print(f"- Precio: {precios_validos}")
print("     Valores: gratuito, bajo (menos de 10€), medio (entre 10 y 30€) y alto (más de 30€)")
print(f"- Categorías: {categorias}")
print("- Subcategorías por categoría:")
for cat, subs in subcategorias.items():
    print(f"   · {cat}: {subs}")

🎯 Posibles valores para cada condición:
- Rango de edad: [(0, 3), (4, 6), (7, 9), (10, 12), (13, 15), (16, 18)]
- Fecha: formato 'dd/mm/aaaa'
- Día: ['lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado', 'domingo', 'día de semana', 'fin de semana']
- Periodicidad: ['diaria', 'semanal', 'quincenal', 'mensual']
- Horario: ['mañana', 'mediodía', 'tarde', 'noche']
     Horarios; mañana (de 7 a 12h), mediodía (de 12 a 15h), tarde (de 15 a 19h) y noche (de 19 a 7h)
- Estación: ['verano', 'invierno']
     Unicamente se admite verano (de junio a septiembre) o invierno (de diciembre a febrero)
- Duración: ['corta', 'media', 'larga']
     Intervalos: admite corta (1 día), media (entre 1 y 7 días) o larga (más de 7 días)
- Distritos de Madrid: ['Centro', 'Arganzuela', 'Retiro', 'Salamanca', 'Chamartín', 'Tetuán', 'Chamberí', 'Fuencarral-El Pardo', 'Moncloa-Aravaca', 'Latina', 'Carabanchel', 'Usera', 'Puente de Vallecas', 'Moratalaz', 'Ciudad Lineal', 'Hortaleza', 'Villaverde', 'Villa de Vallecas', 'Vicálvaro', 'San Blas-Canillejas', 'Barajas']
- Ciudad: Madrid (obligatoria)
- Precio: ['gratuito', 'bajo', 'medio', 'alto']
     Valores: gratuito, bajo (menos de 10€), medio (entre 10 y 30€) y alto (más de 30€)
- Categorías: ['La Ciudad', 'Cultura y Espectáculos', 'Educación', 'Aire Libre', 'Deporte']
- Subcategorías por categoría:
   · La Ciudad: ['Actividades', 'Carnaval', 'Semana Santa', 'Verano', 'Centros de Atención a Las Familias', 'Navidad']
   · Cultura y Espectáculos: ['Cuentacuentos', 'Títeres y marionetas', 'Magia', 'Club de lectura', 'Cine Infantil', 'Circo', 'Conciertos', 'Exposiciones', 'Monumentos', 'Museos', 'Proyecciones', 'Talleres', 'Teatro Infantil', 'Música', 'Bailes']
   · Educación: ['Ayudas y Becas', 'Campamentos Urbanos', 'Ludotecas', 'Idiomas']
   · Aire Libre: ['Actividades al Aire Libre', 'Actividades con animales', 'Parques y jardines']
   · Deporte: ['Deportes de aventura', 'Deportes de invierno', 'Deportes acuáticos', 'Deportes de cancha', 'Rocódromos', 'Deporte en la calle', 'Carreras y eventos']

In [12]:
# Aquí introduce el usuario sus condiciones (ejemplo de prueba)
condiciones_usuario = {
    'rango_edad': (4, 6),
    'fecha': '15/05/2025',
    'día': 'sábado',
    'periodicidad': 'semanal',
    'horario': 'mañana',
    'estación': '',
    'duración': 'corta',
    'distrito': 'Centro',
    'ciudad': 'Madrid',
    'precio': 'gratuito',
    'categoría': 'Cultura y espectáculos',
    'subcategoría': 'Teatro Infantil'
}

# Validaciones básicas
if 'ciudad' not in condiciones_usuario or condiciones_usuario['ciudad'].strip().lower() != 'madrid':
    print("\n⚠️  Modelo desarrollado solo para actividades en Madrid. Por favor, introduce 'Madrid' como ciudad.")
else:
    if 'categoría' in condiciones_usuario:
        categoria = condiciones_usuario['categoría']
        if categoria not in categorias:
            print(f"\n⚠️  Categoría inválida: {categoria}")
        elif 'subcategoría' in condiciones_usuario:
            subcat = condiciones_usuario['subcategoría']
            if subcat not in subcategorias[categoria]:
                print(f"\n⚠️  Subcategoría inválida: '{subcat}' no está en la categoría '{categoria}'")

# Mostrar condiciones introducidas
print("\n📝 Condiciones introducidas por el usuario:")
for k, v in condiciones_usuario.items():
    print(f" - {k}: {v}")

⚠️  Categoría inválida: Cultura y espectáculos

📝 Condiciones introducidas por el usuario:
 - rango_edad: (4, 6)
 - fecha: 15/05/2025
 - día: sábado
 - periodicidad: semanal
 - horario: mañana
 - estación:
 - duración: corta
 - distrito: Centro
 - ciudad: Madrid
 - precio: gratuito
 - categoría: Cultura y espectáculos
 - subcategoría: Teatro Infantil

In [144]:
# Celda de prueba para probar filtrado
condiciones_usuario = {
    'distrito':'chamberí',
    #'fecha':'15/05/2025',
    # 'día':'sábado',
    'horario':'manana',
   'precio':'gratuito'
}

Ahora introduzco una función de validación de las condiciones introducidas. Si alguna no se ha introducido, o no es valida se deja vacía. Madrid es condición obligatoria, saltaría un mensaje de error.

He introducido una normalización, para aceptar mayúsculas/ minúsculas, con y sin acentos.

In [76]:
# Funciones para normalizar 
import unicodedata
def normalizar(texto):
    if not isinstance(texto, str):
        return texto
    texto = texto.lower().strip()
    texto = unicodedata.normalize('NFD', texto)
    texto = ''.join(c for c in texto if unicodedata.category(c) != 'Mn')
    return texto

In [69]:
# Función para validar condiciones introducidas por el usuario
from datetime import datetime
def validar_condiciones_usuario(condiciones_usuario):
    errores = []

    # Listas de valores válidos (sin normalizar, para referencia final)
    categorias = [
        "La Ciudad", "Cultura y Espectáculos", "Educación", "Aire Libre", "Deporte"
    ]
    subcategorias = {
        "La Ciudad": ["Actividades", "Carnaval", "Semana Santa", "Verano", "Centros de Atención a Las Familias", "Navidad"],
        "Cultura y Espectáculos": ["Cuentacuentos", "Títeres y marionetas", "Magia", "Club de lectura", "Cine Infantil", 
                                "Circo", "Conciertos", "Exposiciones", "Monumentos", "Museos", "Proyecciones", 
                                "Talleres", "Teatro Infantil", "Música", "Bailes"],
        "Educación": ["Ayudas y Becas", "Campamentos Urbanos", "Ludotecas", "Idiomas"],
        "Aire Libre": ["Actividades al Aire Libre", "Actividades con animales", "Parques y jardines"],
        "Deporte": ["Deportes de aventura", "Deportes de invierno", "Deportes acuáticos", "Deportes de cancha", 
                    "Rocódromos", "Deporte en la calle", "Carreras y eventos"]
    }
    rango_edades_validos = [(0, 3), (4, 6), (7, 9), (10, 12), (13, 15), (16, 18)]
    dias_validos = ["lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "día de semana", "fin de semana"]
    periodicidad_valida = ["diaria", "semanal", "quincenal", "mensual"]
    horarios_validos = ["mañana", "mediodía", "tarde", "noche"]
    estaciones_validas = ["verano", "invierno"]
    duraciones_validas = ["corta", "media", "larga"]
    distritos_madrid = ['Centro', 'Arganzuela', 'Retiro', 'Salamanca', 'Chamartín', 'Tetuán', 'Chamberí',
                        'Fuencarral-El Pardo', 'Moncloa-Aravaca', 'Latina', 'Carabanchel', 'Usera',
                        'Puente de Vallecas', 'Moratalaz', 'Ciudad Lineal', 'Hortaleza', 'Villaverde',
                        'Villa de Vallecas', 'Vicálvaro', 'San Blas-Canillejas', 'Barajas']
    precios_validos = ["gratuito", "bajo", "medio", "alto"]

    claves_validas = {
        'rango_edad', 'fecha', 'día', 'periodicidad', 'horario', 'estación', 'duración',
        'distrito', 'ciudad', 'precio', 'categoría', 'subcategoría'
    }

    if not condiciones_usuario:
        errores.append("Debe introducirse al menos una condición.")
        return errores

    # Detectar claves no reconocidas
    for clave in condiciones_usuario:
        if clave not in claves_validas:
            errores.append(f"Clave no reconocida: '{clave}'")

   # Validar ciudad
    ciudad = condiciones_usuario.get('ciudad', '')
    if not ciudad:
        print("📍 Ciudad no proporcionada. Te mostramos las actividades en 'Madrid', ciudad en la que estamos trabajando actualmente.")
    elif normalizar(ciudad) != 'madrid':
        print("⚠️ Ciudad inválida. Te mostramos las actividades en 'Madrid', ciudad en la que estamos trabajando actualmente.")
        condiciones_usuario ['ciudad'] = 'Madrid'


    # Validar rango de edad
    if 'rango_edad' in condiciones_usuario:
        if condiciones_usuario['rango_edad'] not in rango_edades_validos:
            errores.append(f"Rango de edad inválido: {condiciones_usuario['rango_edad']}")

    # Validar fecha
    if 'fecha' in condiciones_usuario:
        try:
            datetime.strptime(condiciones_usuario['fecha'], "%d/%m/%Y")
        except ValueError:
            errores.append(f"Formato de fecha inválido: {condiciones_usuario['fecha']} (debe ser dd/mm/aaaa)")

    # Validar día
    if 'día' in condiciones_usuario:
        dia = normalizar(condiciones_usuario['día'])
        if dia not in list(map(normalizar, dias_validos)):
            errores.append(f"Día inválido: {condiciones_usuario['día']}")
            
    # Periodicidad
    if 'periodicidad' in condiciones_usuario:
        periodicidad = normalizar(condiciones_usuario['periodicidad'])
        if periodicidad not in list(map(normalizar, periodicidad_valida)):
            errores.append(f"Periodicidad inválida: {condiciones_usuario['periodicidad']}")


    # Horario
    if 'horario' in condiciones_usuario:
        horario = normalizar(condiciones_usuario['horario'])
        if horario not in list(map(normalizar, horarios_validos)):
            errores.append(f"Horario inválido: {condiciones_usuario['horario']}")

    # Estación
    if 'estación' in condiciones_usuario and condiciones_usuario['estación']:
        estacion = normalizar(condiciones_usuario['estación'])
        if estacion not in list(map(normalizar, estaciones_validas)):
            errores.append(f"Estación inválida: {condiciones_usuario['estación']}")

    # Duración
    if 'duración' in condiciones_usuario:
        duracion = normalizar(condiciones_usuario['duración'])
        if duracion not in list(map(normalizar, duraciones_validas)):
            errores.append(f"Duración inválida: {condiciones_usuario['duración']}")

    # Distrito
    if 'distrito' in condiciones_usuario:
        distrito = normalizar(condiciones_usuario['distrito'])
        if distrito not in list(map(normalizar, distritos_madrid)):
            errores.append(f"Distrito inválido: {condiciones_usuario['distrito']}")

    # Precio
    if 'precio' in condiciones_usuario:
        precio = normalizar(condiciones_usuario['precio'])
        if precio not in list(map(normalizar, precios_validos)):
            errores.append(f"Precio inválido: {condiciones_usuario['precio']}")

    # Categoría y Subcategoría
    if 'categoría' in condiciones_usuario:
        cat_usuario = condiciones_usuario['categoría']
        cat_normal = normalizar(cat_usuario)
        cat_match = None
        for cat in categorias:
            if normalizar(cat) == cat_normal:
                cat_match = cat
                break
        if not cat_match:
            errores.append(f"Categoría inválida: {cat_usuario}")
        else:
            if 'subcategoría' in condiciones_usuario:
                subcat_usuario = condiciones_usuario['subcategoría']
                subcat_normal = normalizar(subcat_usuario)
                subcat_match = [s for s in subcategorias[cat_match] if normalizar(s) == subcat_normal]
                if not subcat_match:
                    errores.append(f"Subcategoría inválida: '{subcat_usuario}' no pertenece a la categoría '{cat_match}'")

    return True if not errores else errores

In [117]:
resultado = validar_condiciones_usuario(condiciones_usuario)
if resultado is True:
    print("✅ Condiciones válidas.")
else:
    print("❌ Errores encontrados:")
    for err in resultado:
        print(f" - {err}")

📍 Ciudad no proporcionada. Te mostramos las actividades en 'Madrid', ciudad en la que estamos trabajando actualmente.
✅ Condiciones válidas.

Ahora he de filtrar mi dataframe original según las condiciones estipuladas por el usuario/ cliente.

In [88]:
df_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   título                261 non-null    string
 1   descripción           237 non-null    string
 2   categoría             261 non-null    string
 3   subcategoría          261 non-null    string
 4   edad_min              156 non-null    Int64
 5   edad_max              156 non-null    Int64
 6   requiere_inscripcion  63 non-null     boolean
 7   periodicidad          16 non-null     string
 8   día_días              259 non-null    string
 9   hora_inicio           236 non-null    string
 10  hora_fin              38 non-null     string
 11  fecha_inicio          256 non-null    string
 12  fecha_fin             256 non-null    string
 13  ciudad                261 non-null    string
 14  distrito              217 non-null    string
 15  precio_valor          251 non-null    Int64
 16  recomendado           261 non-null    boolean
 17  tiene_url_info        261 non-null    boolean
 18  tiene_url_imagen      261 non-null    boolean
dtypes: Int64(3), boolean(4), string(12)
memory usage: 33.5 KB

In [146]:
# Función de filtrado de los datos según condiciones usuario
import pandas as pd

def filtrado_segun_condiciones(df, condiciones):
    df_filtrado = df.copy()

    # --- Función de normalización ---
    def normalizar(texto):
        return str(texto).strip().lower()

    # --- Validación obligatoria: ciudad ---
    if 'ciudad' not in condiciones or normalizar(condiciones['ciudad']) != 'madrid':
        print("📍 Ciudad no proporcionada o inválida. Te mostramos las actividades en 'Madrid', ciudad en la que estamos trabajando actualmente.")
        condiciones['ciudad'] = 'Madrid'
    df_filtrado = df_filtrado[df_filtrado['ciudad'].str.lower() == 'madrid']
    
    # --- Normalización de tipos de columnas ---
    df_filtrado['edad_min'] = pd.to_numeric(df_filtrado['edad_min'], errors='coerce')
    df_filtrado['edad_max'] = pd.to_numeric(df_filtrado['edad_max'], errors='coerce')
    df_filtrado['fecha_inicio'] = pd.to_datetime(df_filtrado['fecha_inicio'], errors='coerce', dayfirst = True)
    df_filtrado['fecha_fin'] = pd.to_datetime(df_filtrado['fecha_fin'], errors='coerce', dayfirst = True)
    df_filtrado['precio_valor'] = pd.to_numeric(df_filtrado['precio_valor'], errors='coerce')

    # --- Filtro por rango de edad ---
    if 'rango_edad' in condiciones and condiciones['rango_edad']:
        edad_min, edad_max = condiciones['rango_edad']
        df_filtrado = df_filtrado[
            (df_filtrado['edad_max'] >= edad_min) & (df_filtrado['edad_min'] <= edad_max)
        ]

    # --- Filtro por fecha específica ---
    if 'fecha' in condiciones and condiciones['fecha']:
        fecha_usuario = pd.to_datetime(condiciones['fecha'], dayfirst=True, errors='coerce')
        if pd.notna(fecha_usuario):
            df_filtrado = df_filtrado[
                (df_filtrado['fecha_inicio'] <= fecha_usuario) & 
                (df_filtrado['fecha_fin'] >= fecha_usuario)
            ]

    # --- Filtro por día ---
    if 'día' in condiciones and condiciones['día']:
        dia = normalizar(condiciones['día'])
        if dia == "fin de semana":
            df_filtrado = df_filtrado[df_filtrado['día_días'].apply(normalizar).isin(["sábado", "domingo"])]
        elif dia == "día de semana":
            df_filtrado = df_filtrado[~df_filtrado['día_días'].apply(normalizar).isin(["sábado", "domingo"])]
        else:
            df_filtrado = df_filtrado[df_filtrado['día_días'].apply(normalizar) == dia]
    
    # --- Filtro por periodicidad ---
    if 'periodicidad' in condiciones and condiciones['periodicidad']:
        periodicidad = normalizar(condiciones['periodicidad'])
        df_filtrado = df_filtrado[
            df_filtrado['periodicidad'].apply(lambda x: normalizar(str(x))) == periodicidad
        ]

    # --- Filtro por horario ---
    if 'horario' in condiciones and condiciones['horario']:
        horario = normalizar(condiciones['horario'])

        # Filtra solo las filas que tienen hora_inicio no nulo
        df_horas = df_filtrado[df_filtrado['hora_inicio'].notnull()].copy()
        
        # Extrae la hora como número (por ejemplo 14.5 para 14:30)
        def hora_a_decimal(hora_str):
            try:
                h, m = map(int, hora_str.split(':'))
                return h + m / 60
            except:
                return None  # si falla la conversión, devuelve None

        df_horas['hora_decimal'] = df_horas['hora_inicio'].apply(hora_a_decimal)

        # Aplica el filtrado según el tramo horario
        if horario == normalizar ("mañana"):
            df_filtrado = df_horas[(df_horas['hora_decimal'] >= 7) & (df_horas['hora_decimal'] < 12)]
        elif horario == normalizar ("mediodía"):
            df_filtrado = df_horas[(df_horas['hora_decimal'] >= 12) & (df_horas['hora_decimal'] < 15)]
        elif horario == normalizar ("tarde"):
            df_filtrado = df_horas[(df_horas['hora_decimal'] >= 15) & (df_horas['hora_decimal'] < 19)]
        elif horario == normalizar ("noche"):
            df_filtrado = df_horas[(df_horas['hora_decimal'] >= 19) | (df_horas['hora_decimal'] < 7)]

        # Elimina la columna auxiliar si no la necesitas
        df_filtrado = df_filtrado.drop(columns=['hora_decimal'], errors= 'ignore')


    # --- Filtro por estación ---
    if 'estación' in condiciones and condiciones['estación']:
        estacion = normalizar(condiciones['estación'])
        mes_inicio = df_filtrado['fecha_inicio'].dt.month
        if estacion == 'verano':
            df_filtrado = df_filtrado[mes_inicio.isin([6, 7, 8, 9])]
        elif estacion == 'invierno':
            df_filtrado = df_filtrado[mes_inicio.isin([12, 1, 2])]

    # --- Filtro por duración ---
    if 'duración' in condiciones and condiciones['duración']:
        duracion_dias = (df_filtrado['fecha_fin'] - df_filtrado['fecha_inicio']).dt.days + 1
        duracion = normalizar(condiciones['duración'])
        if duracion == "corta":
            df_filtrado = df_filtrado[duracion_dias <= 1]
        elif duracion == "media":
            df_filtrado = df_filtrado[(duracion_dias > 1) & (duracion_dias <= 7)]
        elif duracion == "larga":
            df_filtrado = df_filtrado[duracion_dias > 7]

    # --- Filtro por distrito ---
    if 'distrito' in condiciones and condiciones['distrito']:
        distrito = normalizar(condiciones['distrito'])
        df_filtrado = df_filtrado[df_filtrado['distrito'].apply(normalizar) == distrito]

    # --- Filtro por ciudad ---
    if 'ciudad' in condiciones and condiciones['ciudad']:
        ciudad = normalizar(condiciones['ciudad'])
        df_filtrado = df_filtrado[df_filtrado['ciudad'].apply(normalizar) == ciudad]

    # --- Filtro por precio ---
    if 'precio' in condiciones and condiciones['precio']:
        precio = normalizar(condiciones['precio'])
        if precio == "gratuito":
            df_filtrado = df_filtrado[df_filtrado['precio_valor'] == 0]
        elif precio == "bajo":
            df_filtrado = df_filtrado[(df_filtrado['precio_valor'] > 0) & (df_filtrado['precio_valor'] < 10)]
        elif precio == "medio":
            df_filtrado = df_filtrado[(df_filtrado['precio_valor'] >= 10) & (df_filtrado['precio_valor'] <= 30)]
        elif precio == "alto":
            df_filtrado = df_filtrado[df_filtrado['precio_valor'] > 30]

    # --- Filtro por categoría ---
    if 'categoría' in condiciones and condiciones['categoría']:
        categoria = normalizar(condiciones['categoría'])
        df_filtrado = df_filtrado[df_filtrado['categoría'].apply(normalizar) == categoria]

    # --- Filtro por subcategoría ---
    if 'subcategoría' in condiciones and condiciones['subcategoría']:
        subcategoria = normalizar(condiciones['subcategoría'])
        df_filtrado = df_filtrado[df_filtrado['subcategoría'].apply(normalizar) == subcategoria]

    print(df_filtrado.shape)
    return df_filtrado

In [142]:
df_original.iloc[[53,88,105,129,133,197, 203]]

,título,descripción,categoría,subcategoría,edad_min,edad_max,requiere_inscripcion,periodicidad,día_días,hora_inicio,hora_fin,fecha_inicio,fecha_fin,ciudad,distrito,precio_valor,recomendado,tiene_url_info,tiene_url_imagen
53,"Exposición ""Fervor""",Kike García. Fernando Sevillano,Cultura y Espectáculos,Exposiciones,<NA>,<NA>,<NA>,<NA>,"lunes, jueves",<NA>,<NA>,05/05/2025,15/05/2025,Madrid,Chamberí,0,True,True,True
88,Cuentacuentos - La Flor más Bonita del Mundo,Sin descripción,No especificada,No especificada,<NA>,<NA>,<NA>,<NA>,sábado,11:00,<NA>,10/05/2025,10/05/2025,Madrid,Chamberí,0,True,True,True
105,Teatro Familiar - Texturas,Sin descripción,Cultura y Espectáculos,Teatro Infantil,1,6,<NA>,<NA>,domingo,18:00,<NA>,11/05/2025,11/05/2025,Madrid,Chamberí,0,True,True,True
129,Actividades infantiles de San Isidro,Sin descripción,No especificada,No especificada,<NA>,<NA>,<NA>,<NA>,jueves,17:30,<NA>,15/05/2025,15/05/2025,Madrid,Chamberí,0,True,True,True
133,Actividades Infantiles,Plaza de Chamberí.,No especificada,No especificada,<NA>,<NA>,<NA>,<NA>,jueves,17:30,<NA>,15/05/2025,15/05/2025,Madrid,Chamberí,0,True,True,True
197,Concierto - A Ambos Lados del Atlántico 2,Sin descripción,Cultura y Espectáculos,Conciertos. Música,<NA>,<NA>,<NA>,<NA>,sábado,19:00,<NA>,24/05/2025,24/05/2025,Madrid,Chamberí,0,True,True,True
203,Folklore en Familia: concierto de Vibra-Tó - C...,Joaquín y Miguel llevan más de 20 años creando...,Cultura y Espectáculos,Conciertos. Música,<NA>,<NA>,<NA>,<NA>,domingo,12:30,<NA>,25/05/2025,25/05/2025,Madrid,Chamberí,0,True,False,True

In [148]:
condiciones_usuario

{'distrito': 'chamberí',
 'horario': 'manana',
 'precio': 'gratuito',
 'ciudad': 'Madrid'}

In [147]:
filtrado_segun_condiciones(df_original, condiciones_usuario)

(10, 19)

,título,descripción,categoría,subcategoría,edad_min,edad_max,requiere_inscripcion,periodicidad,día_días,hora_inicio,hora_fin,fecha_inicio,fecha_fin,ciudad,distrito,precio_valor,recomendado,tiene_url_info,tiene_url_imagen
53,"Exposición ""Fervor""",Kike García. Fernando Sevillano,Cultura y Espectáculos,Exposiciones,<NA>,<NA>,<NA>,<NA>,"lunes, jueves",<NA>,<NA>,2025-05-05,2025-05-15,Madrid,Chamberí,0,True,True,True
88,Cuentacuentos - La Flor más Bonita del Mundo,Sin descripción,No especificada,No especificada,<NA>,<NA>,<NA>,<NA>,sábado,11:00,<NA>,2025-05-10,2025-05-10,Madrid,Chamberí,0,True,True,True
105,Teatro Familiar - Texturas,Sin descripción,Cultura y Espectáculos,Teatro Infantil,1,6,<NA>,<NA>,domingo,18:00,<NA>,2025-05-11,2025-05-11,Madrid,Chamberí,0,True,True,True
129,Actividades infantiles de San Isidro,Sin descripción,No especificada,No especificada,<NA>,<NA>,<NA>,<NA>,jueves,17:30,<NA>,2025-05-15,2025-05-15,Madrid,Chamberí,0,True,True,True
133,Actividades Infantiles,Plaza de Chamberí.,No especificada,No especificada,<NA>,<NA>,<NA>,<NA>,jueves,17:30,<NA>,2025-05-15,2025-05-15,Madrid,Chamberí,0,True,True,True
197,Concierto - A Ambos Lados del Atlántico 2,Sin descripción,Cultura y Espectáculos,Conciertos. Música,<NA>,<NA>,<NA>,<NA>,sábado,19:00,<NA>,2025-05-24,2025-05-24,Madrid,Chamberí,0,True,True,True
203,Folklore en Familia: concierto de Vibra-Tó - C...,Joaquín y Miguel llevan más de 20 años creando...,Cultura y Espectáculos,Conciertos. Música,<NA>,<NA>,<NA>,<NA>,domingo,12:30,<NA>,2025-05-25,2025-05-25,Madrid,Chamberí,0,True,False,True
204,Folklore en Familia: taller de Vibra-Tó - Cham...,Te gustaría aprender a fabricar tu propio inst...,Cultura y Espectáculos,Talleres,0,7,True,<NA>,domingo,11:00,<NA>,2025-05-25,2025-05-25,Madrid,Chamberí,0,True,False,True
214,Taller y concierto infantil - Vibra Tó,Sin descripción,Cultura y Espectáculos,Conciertos. Música. Talleres,<NA>,<NA>,<NA>,<NA>,domingo,11:00,<NA>,2025-05-25,2025-05-25,Madrid,Chamberí,0,True,True,True
242,Coral voces bravas,Coro Therpsicore. Aquellas pequeñas cosas.,No especificada,No especificada,<NA>,<NA>,<NA>,<NA>,sábado,19:00,<NA>,2025-05-31,2025-05-31,Madrid,Chamberí,0,True,True,True

In [127]:
df_filtrado = filtrado_segun_condiciones(df_original, condiciones_usuario)

(3, 20)

In [48]:
if 'día' in condiciones_usuario and condiciones_usuario['día']:
    print(normalizar(condiciones_usuario['día']))

In [30]:
print(df_filtrado['día_días'].unique())
print(df_filtrado['día_días'].apply(normalizar).unique())

<StringArray>
['lunes, jueves', 'sábado', 'domingo', 'jueves']
Length: 4, dtype: string
['lunes, jueves' 'sabado' 'domingo' 'jueves']

In [51]:
pd.set_option('display.max_columns', None)
df_filtrado[df_filtrado.isnull().any(axis=1)]

,título,descripción,categoría,subcategoría,edad_min,edad_max,requiere_inscripcion,periodicidad,día_días,hora_inicio,hora_fin,fecha_inicio,fecha_fin,ciudad,distrito,precio_valor,recomendado,tiene_url_info,tiene_url_imagen
53,"Exposición ""Fervor""",Kike García. Fernando Sevillano,Cultura y Espectáculos,Exposiciones,<NA>,<NA>,<NA>,<NA>,"lunes, jueves",<NA>,<NA>,2025-05-05,2025-05-15,Madrid,Chamberí,0,True,True,True
88,Cuentacuentos - La Flor más Bonita del Mundo,Sin descripción,No especificada,No especificada,<NA>,<NA>,<NA>,<NA>,sábado,<NA>,<NA>,2025-05-10,2025-05-10,Madrid,Chamberí,0,True,True,True
105,Teatro Familiar - Texturas,Sin descripción,Cultura y Espectáculos,Teatro Infantil,1,6,<NA>,<NA>,domingo,<NA>,<NA>,2025-05-11,2025-05-11,Madrid,Chamberí,0,True,True,True
129,Actividades infantiles de San Isidro,Sin descripción,No especificada,No especificada,<NA>,<NA>,<NA>,<NA>,jueves,<NA>,<NA>,2025-05-15,2025-05-15,Madrid,Chamberí,0,True,True,True
133,Actividades Infantiles,Plaza de Chamberí.,No especificada,No especificada,<NA>,<NA>,<NA>,<NA>,jueves,<NA>,<NA>,2025-05-15,2025-05-15,Madrid,Chamberí,0,True,True,True
197,Concierto - A Ambos Lados del Atlántico 2,Sin descripción,Cultura y Espectáculos,Conciertos. Música,<NA>,<NA>,<NA>,<NA>,sábado,<NA>,<NA>,2025-05-24,2025-05-24,Madrid,Chamberí,0,True,True,True
203,Folklore en Familia: concierto de Vibra-Tó - C...,Joaquín y Miguel llevan más de 20 años creando...,Cultura y Espectáculos,Conciertos. Música,<NA>,<NA>,<NA>,<NA>,domingo,<NA>,<NA>,2025-05-25,2025-05-25,Madrid,Chamberí,0,True,False,True
204,Folklore en Familia: taller de Vibra-Tó - Cham...,Te gustaría aprender a fabricar tu propio inst...,Cultura y Espectáculos,Talleres,0,7,True,<NA>,domingo,<NA>,<NA>,2025-05-25,2025-05-25,Madrid,Chamberí,0,True,False,True
214,Taller y concierto infantil - Vibra Tó,Sin descripción,Cultura y Espectáculos,Conciertos. Música. Talleres,<NA>,<NA>,<NA>,<NA>,domingo,<NA>,<NA>,2025-05-25,2025-05-25,Madrid,Chamberí,0,True,True,True
242,Coral voces bravas,Coro Therpsicore. Aquellas pequeñas cosas.,No especificada,No especificada,<NA>,<NA>,<NA>,<NA>,sábado,<NA>,<NA>,2025-05-31,2025-05-31,Madrid,Chamberí,0,True,True,True

## Generación dataframe filtrado para ML

In [31]:
df_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 53 to 242
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   título                10 non-null     string
 1   descripción           10 non-null     string
 2   categoría             10 non-null     string
 3   subcategoría          10 non-null     string
 4   edad_min              2 non-null      Int64
 5   edad_max              2 non-null      Int64
 6   requiere_inscripcion  1 non-null      boolean
 7   periodicidad          0 non-null      string
 8   día_días              10 non-null     string
 9   hora_inicio           0 non-null      Float64
 10  hora_fin              0 non-null      string
 11  fecha_inicio          10 non-null     datetime64[ns]
 12  fecha_fin             10 non-null     datetime64[ns]
 13  ciudad                10 non-null     string
 14  distrito              10 non-null     string
 15  precio_valor          10 non-null     Int64
 16  recomendado           10 non-null     boolean
 17  tiene_url_info        10 non-null     boolean
 18  tiene_url_imagen      10 non-null     boolean
dtypes: Float64(1), Int64(3), boolean(4), datetime64[ns](2), string(9)
memory usage: 1.4 KB

In [32]:
# OPCIÓN 1
import sys
import os
sys.path.append(os.path.abspath('../src/utils'))
from utils_agv import df_to_ml

df_filtrado_ml = df_to_ml(df_filtrado)

df_filtrado_ml

,edad_min,edad_max,requiere_inscripcion,hora_inicio,hora_fin,precio_valor,recomendado,tiene_url_info,tiene_url_imagen,titulo_longitud,...,periodicidad_diaria,periodicidad_semanal,periodicidad_quincenal,periodicidad_mensual,distrito_Chamberí,precio_gratuito,precio_bajo,precio_medio,precio_alto,ciudad_Madrid
53,0,0.499410,0,0.0,<NA>,0,1,1,1,-1.294870,...,0,0,0,0,1,1,0,0,0,1
88,0,0.499410,0,0.0,<NA>,0,1,1,1,0.767025,...,0,0,0,0,1,1,0,0,0,1
105,1,-2.106209,0,0.0,<NA>,0,1,1,1,-0.717540,...,0,0,0,0,1,1,0,0,0,1
129,0,0.499410,0,0.0,<NA>,0,1,1,1,0.107219,...,0,0,0,0,1,1,0,0,0,1
133,0,0.499410,0,0.0,<NA>,0,1,1,1,-1.047443,...,0,0,0,0,1,1,0,0,0,1
197,0,0.499410,0,0.0,<NA>,0,1,1,1,0.519598,...,0,0,0,0,1,1,0,0,0,1
203,0,0.499410,0,0.0,<NA>,0,1,0,1,1.509307,...,0,0,0,0,1,1,0,0,0,1
204,0,-1.889074,1,0.0,<NA>,0,1,0,1,1.261880,...,0,0,0,0,1,1,0,0,0,1
214,0,0.499410,0,0.0,<NA>,0,1,1,1,0.272170,...,0,0,0,0,1,1,0,0,0,1
242,0,0.499410,0,0.0,<NA>,0,1,1,1,-1.377346,...,0,0,0,0,1,1,0,0,0,1

In [33]:
# OPCIÓN 2
import sys
import os
sys.path.append(os.path.abspath('../src'))
from utils import utils_agv

df_filtrado_ml = utils_agv.df_to_ml(df_filtrado)

df_filtrado_ml

,edad_min,edad_max,requiere_inscripcion,hora_inicio,hora_fin,precio_valor,recomendado,tiene_url_info,tiene_url_imagen,titulo_longitud,...,periodicidad_diaria,periodicidad_semanal,periodicidad_quincenal,periodicidad_mensual,distrito_Chamberí,precio_gratuito,precio_bajo,precio_medio,precio_alto,ciudad_Madrid
53,0,0.499410,0,0.0,<NA>,0,1,1,1,-1.294870,...,0,0,0,0,1,1,0,0,0,1
88,0,0.499410,0,0.0,<NA>,0,1,1,1,0.767025,...,0,0,0,0,1,1,0,0,0,1
105,1,-2.106209,0,0.0,<NA>,0,1,1,1,-0.717540,...,0,0,0,0,1,1,0,0,0,1
129,0,0.499410,0,0.0,<NA>,0,1,1,1,0.107219,...,0,0,0,0,1,1,0,0,0,1
133,0,0.499410,0,0.0,<NA>,0,1,1,1,-1.047443,...,0,0,0,0,1,1,0,0,0,1
197,0,0.499410,0,0.0,<NA>,0,1,1,1,0.519598,...,0,0,0,0,1,1,0,0,0,1
203,0,0.499410,0,0.0,<NA>,0,1,0,1,1.509307,...,0,0,0,0,1,1,0,0,0,1
204,0,-1.889074,1,0.0,<NA>,0,1,0,1,1.261880,...,0,0,0,0,1,1,0,0,0,1
214,0,0.499410,0,0.0,<NA>,0,1,1,1,0.272170,...,0,0,0,0,1,1,0,0,0,1
242,0,0.499410,0,0.0,<NA>,0,1,1,1,-1.377346,...,0,0,0,0,1,1,0,0,0,1

Pasamos al modelo de recomendación.

## Modelo KNN

Voy a entrenar dos modelos en paralelo, con los datos completos, y con los datos filtrados, si existe filtro de usuario.

In [ ]:
from sklearn.neighbors import NearestNeighbors

def entrenar_modelo_knn(df_ml, n_vecinos=10):
    modelo = NearestNeighbors(n_neighbors=n_vecinos, metric='euclidean')
    modelo.fit(df_ml)
    return modelo

In [37]:
# Entrena con todos los datos
modelo_knn_global = entrenar_modelo_knn(df_ml)

# Entrena con el DataFrame ya filtrado
modelo_knn_filtrado = entrenar_modelo_knn(df_filtrado_ml)

ValueError: Input X contains NaN.
NearestNeighbors does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [50]:
pd.set_option('display.max_columns', None)
df_ml[df_ml.isnull().any(axis=1)]

Empty DataFrame
Columns: [edad_min, edad_max, requiere_inscripcion, hora_inicio, hora_fin, precio_valor, recomendado, tiene_url_info, tiene_url_imagen, titulo_longitud, descripcion_longitud, titulo_tfidf_0, titulo_tfidf_1, titulo_tfidf_2, titulo_tfidf_3, titulo_tfidf_4, desc_tfidf_0, desc_tfidf_1, desc_tfidf_2, desc_tfidf_3, desc_tfidf_4, categoría_Cultura y Espectáculos, categoría_Deporte, categoría_La Ciudad, categoría_Educación, categoría_Aire Libre, subcategoría_Club de lectura, subcategoría_Títeres y marionetas, subcategoría_Idiomas, subcategoría_Parques y jardines, subcategoría_Carreras y eventos, subcategoría_Verano, subcategoría_Música, subcategoría_Conciertos, subcategoría_Actividades al Aire Libre, subcategoría_Bailes, subcategoría_Talleres, subcategoría_Actividades, subcategoría_Magia, subcategoría_Circo, subcategoría_Actividades con animales, subcategoría_Ludotecas, subcategoría_Exposiciones, subcategoría_Campamentos Urbanos, subcategoría_Proyecciones, subcategoría_Cuentacuentos, subcategoría_Semana Santa, subcategoría_Teatro Infantil, edad_0_3, edad_4_6, edad_7_9, edad_10_12, edad_13_15, edad_16_18, fecha_inicio_year, fecha_inicio_month, fecha_inicio_day, fecha_inicio_dayofweek, fecha_inicio_is_summer, fecha_inicio_is_winter, fecha_inicio_is_weekend, fecha_fin_year, fecha_fin_month, fecha_fin_day, fecha_fin_dayofweek, fecha_fin_is_summer, fecha_fin_is_winter, fecha_fin_is_weekend, duracion_dias, duracion_corta, duracion_media, duracion_larga, hora_inicio_manana, hora_inicio_mediodia, hora_inicio_tarde, hora_inicio_noche, hora_fin_manana, hora_fin_mediodia, hora_fin_tarde, hora_fin_noche, dia_lunes, dia_martes, dia_miércoles, dia_jueves, dia_viernes, dia_sábado, dia_domingo, dia_findesemana, dia_entresemana, periodicidad_diaria, periodicidad_semanal, periodicidad_quincenal, periodicidad_mensual, distrito_Centro, distrito_Puente de Vallecas, distrito_Salamanca, distrito_Usera, distrito_Vicálvaro, distrito_Latina, distrito_Hortaleza, ...]
Index: []

In [49]:
pd.set_option('display.max_columns', None)
df_filtrado_ml[df_filtrado_ml.isnull().any(axis=1)]

,edad_min,edad_max,requiere_inscripcion,hora_inicio,hora_fin,precio_valor,recomendado,tiene_url_info,tiene_url_imagen,titulo_longitud,descripcion_longitud,titulo_tfidf_0,titulo_tfidf_1,titulo_tfidf_2,titulo_tfidf_3,titulo_tfidf_4,desc_tfidf_0,desc_tfidf_1,desc_tfidf_2,desc_tfidf_3,desc_tfidf_4,categoría_Cultura y Espectáculos,categoría_<NA>,subcategoría_<NA>,subcategoría_Exposiciones,subcategoría_Música,subcategoría_Teatro Infantil,subcategoría_Talleres,subcategoría_Conciertos,edad_0_3,edad_4_6,edad_7_9,edad_10_12,edad_13_15,edad_16_18,fecha_inicio_year,fecha_inicio_month,fecha_inicio_day,fecha_inicio_dayofweek,fecha_inicio_is_summer,fecha_inicio_is_winter,fecha_inicio_is_weekend,fecha_fin_year,fecha_fin_month,fecha_fin_day,fecha_fin_dayofweek,fecha_fin_is_summer,fecha_fin_is_winter,fecha_fin_is_weekend,duracion_dias,duracion_corta,duracion_media,duracion_larga,dia_lunes,dia_martes,dia_miércoles,dia_jueves,dia_viernes,dia_sábado,dia_domingo,dia_findesemana,dia_entresemana,periodicidad_diaria,periodicidad_semanal,periodicidad_quincenal,periodicidad_mensual,distrito_Chamberí,precio_gratuito,precio_bajo,precio_medio,precio_alto,ciudad_Madrid
53,0,0.499410,0,0.0,<NA>,0,1,1,1,-1.294870,-0.278404,-0.592835,-0.499152,-0.653038,-0.653038,-0.653038,0.0,0.0,-1.0,-1.0,-1.0,1,0,0,1,0,0,0,0,1,1,1,1,1,1,0.0,0.0,-1.688952,-2.422719,0,0,0,0.0,0.0,-0.673564,-1.441153,0,0,0,3.000000,0,0,1,1,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,1
88,0,0.499410,0,0.0,<NA>,0,1,1,1,0.767025,-0.407894,-0.592835,-0.499152,-0.653038,-0.653038,-0.653038,0.0,0.0,1.0,1.0,1.0,0,1,1,0,0,0,0,0,1,1,1,1,1,1,0.0,0.0,-1.068014,0.269191,0,0,1,0.0,0.0,-1.405698,0.160128,0,0,1,-0.333333,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,1
105,1,-2.106209,0,0.0,<NA>,0,1,1,1,-0.717540,-0.407894,-0.592835,-0.499152,-0.653038,-0.653038,-0.653038,0.0,0.0,1.0,1.0,1.0,1,0,0,0,0,1,0,0,1,1,0,0,0,0,0.0,0.0,-0.943826,0.807573,0,0,1,0.0,0.0,-1.259271,0.960769,0,0,1,-0.333333,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,1
129,0,0.499410,0,0.0,<NA>,0,1,1,1,0.107219,-0.407894,-0.592835,-0.499152,-0.653038,-0.653038,-0.653038,0.0,0.0,1.0,1.0,1.0,0,1,1,0,0,0,0,0,1,1,1,1,1,1,0.0,0.0,-0.447076,-0.807573,0,0,0,0.0,0.0,-0.673564,-1.441153,0,0,0,-0.333333,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,1
133,0,0.499410,0,0.0,<NA>,0,1,1,1,-1.047443,-0.383615,-0.592835,-0.499152,-0.653038,-0.653038,-0.653038,0.0,0.0,-1.0,-1.0,-1.0,0,1,1,0,0,0,0,0,1,1,1,1,1,1,0.0,0.0,-0.447076,-0.807573,0,0,0,0.0,0.0,-0.673564,-1.441153,0,0,0,-0.333333,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,1
197,0,0.499410,0,0.0,<NA>,0,1,1,1,0.519598,-0.407894,2.472326,-0.499152,-0.653038,-0.653038,-0.653038,0.0,0.0,1.0,1.0,1.0,1,0,0,0,1,0,0,1,1,1,1,1,1,1,0.0,0.0,0.670613,0.269191,0,0,1,0.0,0.0,0.644278,0.160128,0,0,1,-0.333333,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,1
203,0,0.499410,0,0.0,<NA>,0,1,0,1,1.509307,2.983130,0.737773,1.866443,1.349018,1.349018,1.349018,1.0,0.0,-1.0,-1.0,-1.0,1,0,0,0,1,0,0,1,1,1,1,1,1,1,0.0,0.0,0.794801,0.807573,0,0,1,0.0,0.0,0.790705,0.960769,0,0,1,-0.333333,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,1
204,0,-1.889074,1,0.0,<NA>,0,1,0,1,1.261880,-0.092262,-0.592835,2.126774,1.569342,1.569342,1.569342,0.0,0.0,-1.0,-1.0,-1.0,1,0,0,0,0,0,1,0,1,1,1,0,0,0,0.0,0.0,0.794801,0.807573,0,0,1,0.0,0.0,0.790705,0.960769,0,0,1,-0.333333,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,1
214,0,0.499410,0,0.0,<NA>,0,1,1,1,0.272170,-0.407894,0.939746,-0.499152,1.652908,1.652908,1.652908,0.0,0.0,1.0,1.0,1.0,1,0,0,0,1,0,1,1,1,1,1,1,1,1,0.0,0.0,0.794801,0.807573,0,0,1,0.0,0.0,0.790705,0.960769,0,0,1,-0.333333,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,1
242,0,0.499410,0,0.0,<NA>,0,1,1,1,-1.377346,-0.189379,-0.592835,-0.499152,-0.653038,-0.653038,-0.653038,0.0,1.0,-1.0,-1.0,-1.0,0,1,1,0,0,0,0,0,1,1,1,1,1,1,0.0,0.0,1.539927,0.269191,0,0,1,0.0,0.0,1.669266,0.160128,0,0,1,-0.333333,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,1

## Recomendación con modelo KNN diseñado

Para mejorar, en la función de uso, incorporo una variable que permita recomendar en diferente modo:
- hard o estrictas, es decir, solo devolver recomendación de actividades que las cumplan todas rigurosamente (o ninguna si no hay) ó 
- soft o flexibles, es decir, que pueda devolver actividades "próximas", que no cumplan estrictamente todas las condiciones

In [ ]:
def recomendar_actividades(condiciones_usuario, modo='hard', k=5):
    validacion = validar_condiciones_usuario(condiciones_usuario)
    if validacion is not True:
        return validacion  # lista de errores

    if modo == 'hard':
        df_filtrado = aplicar_filtros_estrictos(df_original, condiciones_usuario)
        return df_filtrado if not df_filtrado.empty else "No se encontraron coincidencias exactas."

    elif modo == 'soft':
        vector_usuario = vectorizar_condiciones(condiciones_usuario, df_ml, columnas_modelo)
        distancias, indices = knn.kneighbors(vector_usuario, n_neighbors=k)
        return df_original.iloc[indices[0]]

    else:
        return "Modo no válido. Usa 'hard' o 'soft'."

Este modelo podría mejorarse incorporando qué condiciones son 'hard' o 'soft' según necesidades más concretas del usuario. Esto es, por ejemplo, podría ser fija y obligada la fecha, o el día de la semana, pero no el distrito, de forma que aparecería una combinación de ambos funcionamientos.